### ISSUE TITLE
Name clashes in the Rust ecosystem

### ISSUE THREAD

**Issue by djc** [OpenMatchmaking/pathfinder#17]
There are already at least two other Rust projects using the Pathfinder name:

https://crates.io/crates/pathfinder
https://github.com/pcwalton/pathfinder

So you might want to consider picking another name.

**Comment by Relrin** [comment]
Hello, @djc 

Thank you for opening an issue.

To be honest, I'm not sure that crates.io is a good place for storing Rust applications. So, I think that better to left everything as is (and the name of the project as well), at least for the current moment of time.

**Comment by djc** [comment]
Whatever you want! Just an FYI.
